{{- if .Values.ingress.tls -}}
{{- $values := .Values }}
{{- range .Values.ingress.tls -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "app.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "app.chart" $ }}
    app.kubernetes.io/name: {{ include "app.name" $ }}
    app.kubernetes.io/instance: {{ include "app.fullname" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  secretName: {{ .secretName }}
  {{- with .hosts }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{ if or (not (hasKey $values.issuer "ca")) (not ($values.issuer.ca | default false)) }}isCA: true{{ end }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: {{ $values.ingress.issuerName }}
    kind: {{ $values.ingress.issuerKind }}
  # DCOS-60297 Update certificate to comply with Apple security requirements
  # https://support.apple.com/en-us/HT210176
  usages:
    - digital signature
    - key encipherment
    - server auth
    - code signing
{{- end }}
{{- end }}
