{{ if and (.Values.serviceAccount.create) (.Values.rbac.create) }}
apiVersion: rbac.authorization.k8s.io/{{ required "A valid .Values.rbac.apiVersion entry required!" .Values.rbac.apiVersion }}
kind: RoleBinding
metadata:
  name: {{ include "app.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "app.chart" $ }}
    app.kubernetes.io/name: {{ include "app.name" $ }}
    app.kubernetes.io/instance: {{ include "app.fullname" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.roleRef }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default (printf "%s" (include "app.fullname" $))}}
    namespace: {{ $.Release.Namespace }}
{{- end }}
